# Generated by Django 5.2.7 on 2025-11-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottoticket',
            name='round',
            field=models.IntegerField(default=1),
        ),
    ]
